/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "query interval": {                               "en": "Query interval (seconds)",                         "de": "Abfrageintervall (Sekunden)",                      "ru": "Интервал запроса (секунды)",                       "pt": "Intervalo de consulta (segundos)",                 "nl": "Query-interval (seconden)",                        "fr": "Intervalle de requête (secondes)",                 "it": "Intervallo di query (secondi)",                    "es": "Intervalo de consulta (segundos)",                 "pl": "Interwał zapytania (sekundy)",                     "zh-cn": "查询间隔（秒）"},
    "sensebox IDs": {                                 "en": "The IDs of your senseBoxes, separated with commas", "de": "Die IDs Ihrer senseBoxen, durch Komma getrennt",   "ru": "Идентификаторы ваших senseBox, разделенные запятыми", "pt": "Os IDs de seus senseBoxes, separados por vírgulas", "nl": "De ID's van uw senseBoxen, gescheiden door komma's", "fr": "Les identifiants de vos senseBox, séparés par des virgules", "it": "Gli ID dei tuoi senseBox, separati da virgole",    "es": "Los ID de sus senseBoxes, separados por comas",    "pl": "Identyfikatory Twoich senseBoxów oddzielone przecinkami", "zh-cn": "senseBox 的 ID，以逗号分隔"},
    "sensebox adapter settings": {                    "en": "Adapter settings for sensebox",                    "de": "Adaptereinstellungen für sensebox",                "ru": "Настройки адаптера для sensebox",                  "pt": "Configurações do adaptador para sensebox",         "nl": "Adapterinstellingen voor sensebox",                "fr": "Paramètres d'adaptateur pour sensebox",            "it": "Impostazioni dell'adattatore per sensebox",        "es": "Ajustes del adaptador para sensebox",              "pl": "Ustawienia adaptera dla sensebox",                 "zh-cn": "sensebox的适配器设置"},
};