/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
	"sensebox adapter settings": {
		en: "Adapter settings for sensebox",
		de: "Adaptereinstellungen für sensebox",
		ru: "Настройки адаптера для sensebox",
		pt: "Configurações do adaptador para sensebox",
		nl: "Adapterinstellingen voor sensebox",
		fr: "Paramètres d'adaptateur pour sensebox",
		it: "Impostazioni dell'adattatore per sensebox",
		es: "Ajustes del adaptador para sensebox",
		pl: "Ustawienia adaptera dla sensebox",
		"zh-cn": "sensebox的适配器设置",
	},
	option1: {
		en: "option1",
		de: "Option 1",
		ru: "Опция 1",
		pt: "Opção 1",
		nl: "Optie 1",
		fr: "Option 1",
		it: "opzione 1",
		es: "Opción 1",
		pl: "opcja 1",
		"zh-cn": "选项1",
	},
	option2: {
		en: "option2",
		de: "Option 2",
		ru: "вариант 2",
		pt: "opção 2",
		nl: "Optie 2",
		fr: "Option 2",
		it: "opzione 2",
		es: "opcion 2",
		pl: "Opcja 2",
		"zh-cn": "选项2",
	},
};
